### ISSUE TITLE
estimated parameters used in camera undistortion

### ISSUE THREAD

**Issue by Duncan1115** [POSTECH-CVLab/SCNeRF#10]
Hi, thank for your code and works! 
I want to know how the estimated parameters "ray_o_noise" and "ray_d_noise" can be used in camera undistortion?

**Comment by jeongyw12382** [comment]
Hi. This is an interesting issue. 
We have considered the method to extend this work to apply camera undistortion. 
Unfortunately, the current non-linear distortions are challenging to undistort.
This kind of inspiration could be somewhat an extension of our work.

**Comment by jeongyw12382** [comment]
Closing the issue since there is no update.
