### ISSUE TITLE
Scripts for paper's results

### ISSUE THREAD

**Issue by bell-one** [POSTECH-CVLab/SCNeRF#11]
Thanks for you wonderful code first,

I'd like to reproduce result on your paper at supplementary Table 3.

But flower dataset with demo.sh goes little bit different way.
Could I get some advice for reproduce setup?

[this](https://wandb.ai/bellone/SCN/runs/2mfp34v6/overview?workspace=) is wandb link in my environment.

Thanks

**Comment by jeongyw12382** [comment]
All the scripts, reported in the paper, are given in the "scripts" folder. Could you check for them? If you have a problem with them, let me know.

**Comment by jeongyw12382** [comment]
Closing the issue.
