### ISSUE TITLE
Parameter setting different with paper

### ISSUE THREAD

**Issue by LOOKCC** [POSTECH-CVLab/SCNeRF#17]
In scripts/main_table_2/fern/main2_fern_ours.sh, last line is:
```
--ft_path logs/main1_fern_nerf/200000.tar
```
which means using main1_fern_nerf to init model.
but this 200000 iter  in table1 nerf setting is trained with `--run_without_colmap both`, 
and in paper the Table2 result is initialized by COLMAP camera information. So the first 200000 iter should be trained with  `--run_without_colmap none`, instead of `--run_without_colmap both`,

According to the description above, there will be conflicts.
And I think maybe it should be
```
--ft_path logs/main2_fern_nerf/200000.tar
```
?

**Comment by jeongyw12382** [comment]
Oh. There was a minor mistake on the script. 
You are right. 
We have changed the order of the tables in the final version so probably several parts remain unchanged. 
I'll change it until this week.

**Comment by jeongyw12382** [comment]
We have changed the script as you've suggested as in the commit below: 
https://github.com/POSTECH-CVLab/SCNeRF/commit/1c32978f0c855ad06e7581640a0bfeb52973b3d3

**Comment by LOOKCC** [comment]
@jeongyw12382  I have another question. I am trying to reproduce the experiment of flower in Table2, 
```
bash scripts/main_table_2/flower/main2_fern_ours.sh
```
And I fix the above mistake by deleting  `--ft_path logs/main1_fern_nerf/200000.tar` .
But my val PSNR is very low compared to train PSNR. I found that the paper has this description in Table 1: "Table 1 reports the qualities of the rendered images in the training set." But there is no such similar description for Table2. So I want to ask the PSNR number in Table2 is the training PSNR or val PSNR ?

**Comment by jeongyw12382** [comment]
Training PSNR is used for the evaluation similar to Table 1. 
The reason here is that we cannot get accurate validation camera parameters since we have already tuned the training camera poses and it is challenging to appropriately align two camera trajectories. 

We are soon going to upload the new version of SCNeRF due to typos in the paper.  
We'll add more descriptions on Table 2 to avoid confusion.
