### ISSUE TITLE
What tool did you use to draw the architecture diagram?

### ISSUE THREAD

**Issue by addy1997** [POSTECH-CVLab/SCNeRF#20]
Hi @joonahn,

This is amazing work! If you don't mind, may I ask you what tool have you used to draw this illustration?

![image](https://user-images.githubusercontent.com/29406906/183307475-8b3c2320-3b00-461a-950f-644f4ccd3397.png)

**Comment by jeongyw12382** [comment]
@joonahn He made this awesome illustration. Could you respond to this issue?

**Comment by joonahn** [comment]
@addy1997 Thanks! I used Adobe Illustrator to draw the figure.
