### ISSUE TITLE
Ablation Study on Tank and Temple datasets

### ISSUE THREAD

**Issue by cv-lab-x** [POSTECH-CVLab/SCNeRF#21]
Hi，
thanks for your great work! i have some questions about applying this work on some large scale datasets.
1.In your paper you did ablation study on LLFF datasets about IE OD PRD, did you do the ablation study on Tank and Temple dataset ?
2.Is it feasible to apply this work on some large scale datasets without initial poses by colmap?
3.In BARF: Bundle-Adjusting Neural Radiance Fields  paper, they mention that it's hard to optimize nerf  and poses because of the position encoding, in your experienments, do you think it is necessary to change the position encoding function as BARF said ?
@chrischoy @minsucho @soskek @joonahn 
Looking forward to your reply!

**Comment by jeongyw12382** [comment]
Oh, Hi. I'm the first author of this paper. 

1. We have not done ablation studies on TNT.
2. Hmm.. we cannot guarantee whether our method works fine on various conditions. 
3. Our concurrent work, NeRF--, also has shown successful performance on similar conditions. So my answer is "it depends."

**Comment by jeongyw12382** [comment]
Please reopen the issue whenever you have more questions. Thanks :)
