### ISSUE TITLE
have bug with the custom image set

### ISSUE THREAD

**Issue by yushengjiexy** [POSTECH-CVLab/SCNeRF#22]
First, i generating COLMAP poses of custom image set. According to my own dataset, i modify Demo.sh. But, it run the following problems.
![image](https://user-images.githubusercontent.com/63044657/190884681-67794794-b78f-4915-88ce-e090b85ba022.png)

**Comment by jeongyw12382** [comment]
Could you provide more details about your custom dataset? 
This seems the estimated keypoints are inconsistent across different views. 
If you are using scenes with many symmetric patterns, SuperGlue could fail.

**Comment by jeongyw12382** [comment]
Closing the issue since no response has been given. Feel free to reopen the issue.
