### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by alien19** [POSTECH-CVLab/SCNeRF#24]
Hello,
I really appreciate your great work!

I tried to run the demo.sh as specified (just changed the number of iterations) but it gave me the following error.

Any advice could be appreciated.
![image](https://user-images.githubusercontent.com/42179967/216948348-1e8bfb5f-c016-4d42-b17b-9f9eb4274416.png)

**Comment by jeongyw12382** [comment]
Could you give me more details about this issue? Did you run the given demo w/o any changes?

**Comment by jeongyw12382** [comment]
Closing the issue since no replies were given the past week

**Comment by alien19** [comment]
> Could you give me more details about this issue? Did you run the given demo w/o any changes?

I'm really sorry for the late reply.
I ran the demo.sh after the number of iterations to 5 and it gave me the aforementioned error.

Edit: I tried also 100 iterations the same error is produced.
also tried to change  the frequency of saving the weights, it didn't help.
