### ISSUE TITLE
How to use pretrained weights for inference on custom datasets?

### ISSUE THREAD

**Issue by sandeepnmenon** [POSTECH-CVLab/SCNeRF#6]
All the scripts mentioned are training the NeRF on a dataset and evaluating them.
Is it possible to run the pretrained model on any set of images captured by a camera?
Or is the pipeline such that the end-end training has to happen for every set of camera images?

**Comment by jeongyw12382** [comment]
I understood your question as to the way of importing trained camera paths before the training stage.
Well, you can touch the parameter initialization part if you want to import your custom camera paths. But the current code only supports importing from the COLMAP camera poses. 
Did I get the right point?

**Comment by jeongyw12382** [comment]
Please reopen the issue if the response was not sufficient.
