### ISSUE TITLE
Question about downsampling factor

### ISSUE THREAD

**Issue by Len-Li** [POSTECH-CVLab/SCNeRF#7]
Hi,
Thanks for sharing your work!

I am confused about the downsampling factor in the LLFF dataset. In your [config](https://github.com/POSTECH-CVLab/SCNeRF/blob/ad8a5d8fe485ea88c1d1072b34e6d0f47dd8e6cc/NeRF/configs/llff_data/fern.txt#L6) file, downsample factor is set to 8. However, in the original [nerf repo](https://github.com/bmild/nerf), downsample factor is set to 4 according to [this](https://github.com/bmild/nerf/blob/18b8aebda6700ed659cb27a0c348b737a5f6ab60/paper_configs/llff_config.txt#L9). I am curious that why do not follow the original setting. This may be unfair for comparision.

**Comment by jeongyw12382** [comment]
For the case of NeRF, our implementation is based on the PyTorch-NeRF, which is publicly available on https://github.com/yenchenlin/nerf-pytorch/blob/master/configs/fern.txt.  If you visit the aforementioned link, the factor value is set to 8. We have followed the setup introduced in the repository to minimize code or setup modification that is already verified. 

Thus, we re-evaluate the baseline model with our code for a fair comparison. 

In addition, based on my experiments in the very early stage of the research, we have not observed large difference using factor 4 and factor 8. However, I have not verified whether there is a large gap between the two factor setups in the final model. 

I hope this description might help you.

**Comment by jeongyw12382** [comment]
Closing the issue. Please reopen the issue whenever you have trouble using the repository.
